all:
	../dskmgr ./wmsx.dsk cp hello.bas
	../dskmgr ./wmsx.dsk cp hoge.bas
	../dskmgr ./image.dsk create hello.bas hoge.bas
	../dskmgr ./image.dsk info
	../dskmgr ./image.dsk ls
	../dskmgr ./image.dsk cp hello.bas
	../dskmgr ./image.dsk cp hoge.bas
